node {
try       {currentBuild.result = "SUCCESS"
stage ('File create') {build job: 'AA', parameters: [string(name: 'File', value: File_P)]}
stage ('File modify') {build job: 'BB', parameters: [string(name: 'File', value: File_P)]}
stage ('File delete') {build job: 'CC', parameters: [string(name: 'File', value: File_P)]}
          }
catch (e) {currentBuild.result = "FAILURE"} 
emailNotify()
}
def emailNotify() {
if ('SUCCESS'.equals(currentBuild.result.toString())){
    emailext (subject: "PASSED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Console output: ${env.BUILD_URL}console".toString(),
                   from: 'zt9074@gmail.com',
                      to: 'zt9074@gmail.com'
              )
                                                      }
if ('FAILURE'.equals(currentBuild.result.toString())) {
    emailext (subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Console output: ${env.BUILD_URL}console".toString(),
                   from: 'zt9074@gmail.com',
                      to: 'zt9074@gmail.com'
              )
						       }
		}
